# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "DeGroote Pulse Links"

# Avatar image path
avatar: "./images/dp_onlylogo.png"

# Name section text
name: "@DeGrootePulse"

# Tagline section text
tagline: >-
    The Student Career Podcast

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-medium"
      text: "Youtube Channel"
      url: "https://www.youtube.com/@DeGrootePulse"
      alt: "DeGroote Pulse Youtube Channel"
      title: "DeGroote Pulse Youtube Channel"
      target: "_blank"
  - link:
      icon: "fa-brands fa-medium"
      text: "Spotify Channel"
      url: "https://open.spotify.com/show/5jEA1ij3KR0ibMhzumlUFw?si=5tXriJ26TkimH22wSmEEMA&nd=1&dlsi=0d4a754acb214d3d"
      alt: "DeGroote Pulse Spotify Channel"
      title: "DeGroote Pulse Spotify Channel"
      target: "_blank"
  - link:
      icon: "fa-brands fa-medium"
      text: "Episode 1"
      url: "https://open.spotify.com/episode/04WQ1qh4gYgZEc3kV38Qtu?si=JVliV9JmTSuABBvIWJuctg"
      alt: "DeGroote Pulse Youtube Channel"
      title: "DeGroote Pulse Youtube Channel"
      target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-medium"
      url: "https://www.youtube.com/@DeGrootePulse"
      title: "DeGroote Pulse Youtube"
      alt: "DeGroote Pulse Youtube"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:degrootepulse@gmail.com"
      title: "Email: degrootepulse@gmail.com"
      alt: "degrootepulse@gmail.com"
      target: "_blank"
